import type { Category } from '@/types';

export const ALL_CATEGORIES: Category[] = [
  { name: 'Travel', id: 13 },
  { name: 'Urban Explore', id: 27 },
  { name: 'Aerial', id: 29 },
  { name: 'Night', id: 30 },
  { name: 'Nature', id: 18 },
  { name: 'Landscapes', id: 8 },
  { name: 'City & Architecture', id: 9 },
  { name: 'Street', id: 21 },
  { name: 'Abstract', id: 10 },
  { name: 'Fine Art', id: 24 },
  { name: 'Black and White', id: 5 },
  { name: 'Animal', id: 11 },
  { name: 'Food', id: 23 },
  { name: 'Macro', id: 12 },
  { name: 'People', id: 7 },
  { name: 'Celebrities', id: 1 },
  { name: 'Fashion', id: 14 },
  { name: 'Sport', id: 17 },
  { name: 'Underwater', id: 22 },
  { name: 'Concert', id: 16 },
  { name: 'Performing Arts', id: 19 },
  { name: 'Still Life', id: 6 },
  { name: 'Transportation', id: 26 },
  { name: 'Wedding', id: 25 },
  { name: 'Commercial', id: 15 },
  { name: 'Journalism', id: 3 },
  { name: 'Uncategorized', id: 0 },
];
