import type { Photo } from '@/types';

export const FALLBACK_PHOTOS: Photo[] = [
  {
    category: 'AERIAL',
    description:
      "Let's see what the new Day brings if you feel lost today. Until the last rays of Sun disappear above the Clouds it feels like in Heaven.\n.\n- NFT available on Foundation.App\n.\nhttps://foundation.app/@2boptik/isob-l-71651\n.",
    height: 2764,
    id: 'dXJpOm5vZGU6UGhvdG86MTAzNTgyMDY4Mg==',
    images: [
      {
        id: 'dXJpOm5vZGU6UGhvdG9SZXNpemVJbWFnZToxMDM1ODIwNjgyLS0tODc2OTg5OS0tLXRydWUtLS0zNQ==',
        jpegUrl: 'local',
        size: 35,
        webpUrl: 'local',
      },
    ],
    legacyId: '1035820682',
    location: '',
    name: 'ISOBƎL',
    notSafeForWork: false,
    photographer: {
      displayName: 'ZweiB-OptiK',
      id: 'dXJpOm5vZGU6VXNlcjo4NzY5ODk5',
      username: 'ZweiB-OptiK',
    },
    tags: [
      'Horizontal',
      'Photography',
      'Tower',
      'Outdoors',
      'Cloud - Sky',
      'Architecture',
      'drone',
      'aerial',
      'sky',
      'sunset',
      'allgäu',
      'bayern',
      'dji',
      'mavic',
      'pro',
      'wetterradar',
      'dream',
      'nft',
      'nftartist',
    ],
    width: 3996,
  },
  {
    category: 'AERIAL',
    description: 'Dead Sea Relaxation',
    height: 3905,
    id: 'dXJpOm5vZGU6UGhvdG86MTA0MDg0MDQ0Nw==',
    images: [
      {
        id: 'dXJpOm5vZGU6UGhvdG9SZXNpemVJbWFnZToxMDQwODQwNDQ3LS0tMjI4NjE3ODctLS1mYWxzZS0tLTM1',
        jpegUrl: 'local',
        size: 35,
        webpUrl: 'local',
      },
    ],
    legacyId: '1040840447',
    location: '',
    name: 'Dead Sea Relaxation',
    notSafeForWork: false,
    photographer: {
      displayName: 'Ruslan Belikov',
      id: 'dXJpOm5vZGU6VXNlcjoyMjg2MTc4Nw==',
      username: 'ruslanbelikov',
    },
    tags: [
      'Water',
      'Nature',
      'Outdoors',
      'Physical Geography',
      'aerial',
      'aerial photo',
      'israel',
      'dead sea',
      'sea',
    ],
    width: 4881,
  },
  {
    category: 'AERIAL',
    description: '冬天的船舶停放处 @签约供稿服务 ',
    height: 1214,
    id: 'dXJpOm5vZGU6UGhvdG86MTA0NjE3MjcyMw==',
    images: [
      {
        id: 'dXJpOm5vZGU6UGhvdG9SZXNpemVJbWFnZToxMDQ2MTcyNzIzLS0tMTAwODY3ODQzMC0tLWZhbHNlLS0tMzU=',
        jpegUrl: 'local',
        size: 35,
        webpUrl: 'local',
      },
    ],
    legacyId: '1046172723',
    location: null,
    name: '停泊在港口的船只的鸟瞰图',
    notSafeForWork: false,
    photographer: {
      displayName: 'X📷',
      id: 'dXJpOm5vZGU6VXNlcjoxMDA4Njc4NDMw',
      username: 'vcg-a690cad9749fdad0a49faacc91edb9011',
    },
    tags: [
      '无人',
      '船',
      '海港',
      '海洋',
      '航拍视角',
      '户外',
      '白昼',
      '游艇',
      '码头',
      '旅行',
      '海滩',
      '高视角',
      '地形',
      '日光',
      '旅游',
    ],
    width: 2048,
  },
  {
    category: 'AERIAL',
    description: 'Croatia',
    height: 3070,
    id: 'dXJpOm5vZGU6UGhvdG86MTA0NTU3NTMxMw==',
    images: [
      {
        id: 'dXJpOm5vZGU6UGhvdG9SZXNpemVJbWFnZToxMDQ1NTc1MzEzLS0tMTAwMjcwMzk3NC0tLWZhbHNlLS0tMzU=',
        jpegUrl: 'local',
        size: 35,
        webpUrl: 'local',
      },
    ],
    legacyId: '1045575313',
    location: 'Luža ul. 4, 20000, Dubrovnik, Хорватия',
    name: 'Dubrovnik city',
    notSafeForWork: false,
    photographer: {
      displayName: 'Alexey Nikitin',
      id: 'dXJpOm5vZGU6VXNlcjoxMDAyNzAzOTc0',
      username: 'nikybwd',
    },
    tags: [
      'Horizontal',
      'Photography',
      'Architecture',
      'Outdoors',
      'Built Structure',
      'Building Exterior',
      'aerial',
      'cityscape',
      'croatia',
    ],
    width: 4639,
  },
  {
    category: 'TRAVEL',
    description:
      'Wasserschloss in der Speicherstadt in Hamburg kurz nach Sonnenuntergang',
    height: 1065,
    id: 'dXJpOm5vZGU6UGhvdG86MTA0MzE3ODU3Mw==',
    images: [
      {
        id: 'dXJpOm5vZGU6UGhvdG9SZXNpemVJbWFnZToxMDQzMTc4NTczLS0tNzI0NTUwMDMtLS1mYWxzZS0tLTM1',
        jpegUrl: 'local',
        size: 35,
        webpUrl: 'local',
      },
    ],
    legacyId: '1043178573',
    location: 'Speicherstadt, 20457 Hamburg, Deutschland',
    name: 'Speicherstadt Hamburg',
    notSafeForWork: false,
    photographer: {
      displayName: 'Tobias Petry',
      id: 'dXJpOm5vZGU6VXNlcjo3MjQ1NTAwMw==',
      username: 'topetry',
    },
    tags: [
      'Hamburg',
      'Speicherstadt',
      'Wasserschloss',
      'Elbe',
      'No People',
      'Architecture',
      'Outdoors',
      'Photography',
      'Illuminated',
      'Horizontal',
      'Travel Destinations',
      'Famous Place',
      'Sky',
      'City',
      'Building Exterior',
      'Reflection',
      'Water',
      'Night',
      'Sunset',
      'River',
      'long exposure',
    ],
    width: 1600,
  },
  {
    category: 'AERIAL',
    description: ' #光影的魅力#  #奇遇人生#  #每一处都有生命# ',
    height: 1150,
    id: 'dXJpOm5vZGU6UGhvdG86MTA0MTY1OTg0OQ==',
    images: [
      {
        id: 'dXJpOm5vZGU6UGhvdG9SZXNpemVJbWFnZToxMDQxNjU5ODQ5LS0tMjQyMTcxMTUtLS1mYWxzZS0tLTM1',
        jpegUrl: 'local',
        size: 35,
        webpUrl: 'local',
      },
    ],
    legacyId: '1041659849',
    location: null,
    name: '养殖业',
    notSafeForWork: false,
    photographer: {
      displayName: '福至心灵',
      id: 'dXJpOm5vZGU6VXNlcjoyNDIxNzExNQ==',
      username: 'vcg-fuzhixinling',
    },
    tags: [],
    width: 2048,
  },
  {
    category: 'TRAVEL',
    description: '',
    height: 3372,
    id: 'dXJpOm5vZGU6UGhvdG86MTA0NTIwNzY4NQ==',
    images: [
      {
        id: 'dXJpOm5vZGU6UGhvdG9SZXNpemVJbWFnZToxMDQ1MjA3Njg1LS0tNzU0NjcwNy0tLXRydWUtLS0zNQ==',
        jpegUrl: 'local',
        size: 35,
        webpUrl: 'local',
      },
    ],
    legacyId: '1045207685',
    location: 'İnle Gölü, Myanmar (Burma)',
    name: 'İnle Lake Myanmar',
    notSafeForWork: false,
    photographer: {
      displayName: 'gürcan kadagan',
      id: 'dXJpOm5vZGU6VXNlcjo3NTQ2NzA3',
      username: 'grcnkdgn',
    },
    tags: [
      'İnle Lake Myanmar',
      'burma',
      'Horizontal',
      'Photography',
      'Buddhism',
      'Religion',
      'Outdoors',
      'Three People',
      'Ceremonial Robe',
      'Spirituality',
      'Standing',
      'Temple - Building',
      'Cultures',
      'Red',
      'Monastery',
      'Window',
      'Pagoda',
    ],
    width: 5059,
  },
  {
    category: 'AERIAL',
    description: '',
    height: 1672,
    id: 'dXJpOm5vZGU6UGhvdG86MTA0MzY4OTYxNg==',
    images: [
      {
        id: 'dXJpOm5vZGU6UGhvdG9SZXNpemVJbWFnZToxMDQzNjg5NjE2LS0tMjQyMzI2NzEtLS1mYWxzZS0tLTM1',
        jpegUrl: 'local',
        size: 35,
        webpUrl: 'local',
      },
    ],
    legacyId: '1043689616',
    location: null,
    name: '《海鲜船》',
    notSafeForWork: false,
    photographer: {
      displayName: '城市穿梭客',
      id: 'dXJpOm5vZGU6VXNlcjoyNDIzMjY3MQ==',
      username: 'vcg-zmpkwxx',
    },
    tags: [
      '海洋',
      '环境',
      '船',
      '海岛',
      '海鲜船',
      '旅游',
      '海鸥',
      '人与自然',
      '海鸟',
      '白鹭',
      '商业',
      '开渔节',
      '禁渔期',
      '渔船',
      '渔民',
      '百舸争流',
      '鱼',
      '虾',
      '螃蟹',
      '鱿鱼',
      '东山岛',
      '舟山群岛',
      '平潭岛',
      '南海',
      '福建',
      '漳州',
      '渔业',
      '自然',
      '生态',
      '满载而归',
      '丰收',
    ],
    width: 2048,
  },
];
