fragment PhotoDiscoverSearchFragment on Query {
  photos: photoDiscoverSearch(
    first: $count
    after: $cursor
    filters: $filters
    sort: $sort
  ) {
    edges {
      node {
        id
        legacyId
        name
        description
        category
        location
        width
        height
        notSafeForWork
        tags
        photographer: uploader {
          id
          username
          displayName
        }
        images(sizes: [35]) {
          id
          size
          jpegUrl
          webpUrl
        }
      }
    }
    pageInfo {
      endCursor
      hasNextPage
    }
  }
}
